### ISSUE TITLE
CE1 busy on Pi 5

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_Blinka#783] opened 2024-01-29 21:07 UTC
I suspect this is really a Blinka Issue.

https://github.com/adafruit/Adafruit_CircuitPython_RFM9x/issues/91

**Comment by makermelissa** [comment] 2024-01-29 21:34
Duplicate of #755. Yep, there's a guide page on how to fix it. I responded in the other issue.

**Closed by makermelissa** 2024-01-29 21:34 UTC
Labels: duplicate
